# Site settings
title: Kaitlyn Keil's Portfolio
description: Kaitlyn Keil's portfolio of projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: KaitlynKeil
user_description: Software engineer with an interest towards adaptive technology and gaming.
user_title: Software Developer
email: kaitlyn.keil@students.olin.edu
twitter_username: 
github_username:  KaitlynKeil
gplus_username: 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
